Código Comercial Uniforme
=========================
Daniel Dias Rodrigues <danieldiasr@gmail.com>

_Copyright , 1987, 1988, 1990, 1991, 1992, 1994, 1995, 1998, 2001, 2004, 2010, 2011, 2012 pelo ``American Law Institute'' e pela ``National Conference of Commissioners on Uniform State Laws''; reproduzido, publicado e distribuído com a permissão do Conselho Editorial Permanente do Código Comercial Uniforme para os fins limitados de estudo, ensino e pesquisa acadêmica._

Nossa coleção tem como objetivo disponibilizar o C.C.U. na versão mais amplamente adotada pelos estados. *Isso significa que nem sempre usaremos a revisão mais recente se essa revisão não tiver alcançado ampla adoção entre as legislaturas americanas.*

Devido a restrições de licença, esta versão do C.C.U. não inclui os comentários oficiais.

''''

Esta é uma tradução do link:https://www.law.cornell.edu/ucc[Uniform Commercial Code] conforme publicado pelo _Legal Information Institute_ da Universidade Cornell.

_O texto desta tradução é copyright de Daniel Dias Rodrigues. Alguns direitos reservados. Os direitos autorais sobre traduções são protegidos pela Convenção de Berna art. 2, alínea 3 (Decreto nº 75.699/75) e pela Lei de Direitos Autorais (``LDA'') art. 7º caput e inciso XI (Lei Federal nº 9.610/98). Esta tradução é distribuída sob os termos da licença link:https://creativecommons.org/licenses/by/4.0/deed.pt_BR[Creative Commons BY 4.0]. Por essa licença tudo é permitido, inclusive alterar a tradução e lucrar com ela sem ter que pagar royalties, desde que você cite o nome do tradutor. Também pela LDA art. 53, inciso II, além do título original, você também é obrigado a citar o nome do tradutor. O tradutor é titular de direitos autorais (LDA art. 14). Isso é um direito moral do autor (LDA art. 24, II). Os direitos morais do autor são inalienáveis e irrenunciáveis (LDA art. 27)._

Para erros de tradução: mailto:danieldiasr@gmail.com[danieldiasr@gmail.com].

''''

== Artigo 2 -- VENDAS (2002)

=== Parte 3 -- OBRIGAÇÃO GERAL E FORMAÇÃO DO CONTRATO

==== § 2-315. Garantia implícita: adequação a um determinado fim.

Quando o vendedor, no momento da contratação, tiver conhecimento de qualquer propósito em particular para o qual o produto é necessário e de que o comprador está contando com a habilidade ou julgamento do vendedor para selecionar ou fornecer o produto adequado, então haverá, a não ser que seja excluída ou modificada na próxima seção, uma garantia implícita de que os produtos serão adequados para esse fim.

==== § 2-316. Exclusão ou modificação de garantias.

. Palavras ou conduta relevantes para a criação de uma garantia expressa e palavras ou conduta tendentes a negar ou limitar a garantia, devem ser interpretadas sempre que possível como consistentes umas com as outras; mas, sujeito às disposições deste Artigo sobre liberdade condicional ou evidência extrínseca (Seção 2-202), a negação ou limitação não terá efeito na medida em que tal interpretação não seja razoável.
. Sujeito à subseção (3), para excluir ou modificar a garantia implícita de comerciabilidade ou qualquer parte dela, o texto deve mencionar a comerciabilidade de forma conspícua, e para excluir ou modificar qualquer garantia implícita de adequação, a exclusão deve ser por escrito e conspícua. A linguagem para excluir todas as garantias
implícitas de adequação será suficiente se ela declarar, por exemplo, que ``Não há garantias que se estendam para além daquelas aqui apresentadas''.
. Não obstante a subseção (2):
.. a menos que as circunstâncias indiquem o contrário, todas as garantias implícitas são excluídas por expressões como ``no estado em que se encontra'', ``com todas as falhas'' ou outra redação que, no entendimento comum, chama a atenção do comprador para a exclusão de garantias e deixa claro que não há nenhuma garantia implícita; e
.. quando o comprador, antes de celebrar o contrato, tiver examinado o produto, a amostra ou o modelo tão completamente quanto ele desejava, ou tiver se recusado a examinar o produto, não haverá garantia implícita no que diz respeito aos defeitos que um exame deveria, nessas circunstâncias, ter revelado para ele; e
.. uma garantia implícita também pode ser excluída ou modificada pelo curso da negociação, pelo curso do desempenho ou pelos usos e costumes do comércio.
. As indenizações por violação de garantia podem ser limitadas conforme as disposições deste Artigo sobre liquidação ou limitação de danos e sobre modificação contratual das indenizações (Seções 2-718 e 2-719).

=== Parte 7 -- MEDIDAS DE REPARAÇÃO

==== § 2-711. Medidas de Reparação do Comprador em Geral; Garantia Real do Comprador sobre Mercadorias Rejeitadas.

. Quando o vendedor não fizer a entrega ou repudiar, ou o comprador rejeitar legitimamente ou revogar justificadamente a aceitação então, em relação a quaisquer mercadorias envolvidas, e em relação ao todo, se a violação abranger todo o contrato (Seção 2-612), o comprador poderá cancelar e, quer o tenha feito ou não, poderá, além de recuperar a parte do preço que foi pago:
.. ``cobrir'' e obter reparação de danos nos termos da próxima seção quanto a todos os bens afetados, tenham ou não sido identificados no contrato; ou
.. obter reparação de danos por não entrega conforme previsto neste Artigo (Seção 2-713).
. Quando o vendedor não entregar ou repudiar, o comprador também poderá:
.. se as mercadorias tiverem sido identificadas, recuperá-las conforme previsto neste Artigo (Seção 2-502); ou
.. em um caso adequado, obter desempenho específico ou reabastecer as mercadorias conforme previsto neste Artigo (Seção 2-716).
. Na rejeição legítima ou revogação justificável da aceitação, um comprador tem uma garantia real sobre os bens em sua posse ou controle por quaisquer pagamentos feitos sobre seu preço e quaisquer despesas razoavelmente incorridas em sua inspeção, recebimento, transporte, cuidado e custódia e pode reter tais bens e revendê-los da mesma maneira que um vendedor lesado (Seção 2-706).

==== § 2-712. ``Cobertura''; Aquisição de bens substitutos pelo comprador.

. Após uma violação da seção anterior, o comprador poderá ``cobrir'', fazendo de boa fé e sem demora injustificada, qualquer compra razoável ou contrato de compra de mercadorias em substituição às devidas pelo vendedor.
. O comprador poderá recuperar do vendedor, como danos, a diferença entre o custo da cobertura e o preço do contrato, juntamente com quaisquer danos incidentais ou consequenciais, conforme definido a seguir (Seção 2-715), subtraídas as despesas economizadas em consequência da violação do vendedor.
. A falha do comprador em efetuar a cobertura dentro desta seção não o impede de obter qualquer outra medida de reparação.

